import { PresetScenario, LogicalInfraComponent } from './types';

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'preset-univ-admission',
    name: 'University Admission Day',
    description: 'High-concurrency result and mark check spike during university admission results release.',
    application: 'student_erp',
    virtualUsers: 500000,
    targetRps: 2500,
    durationSeconds: 120,
    trafficPattern: 'SPIKE',
    cacheEnabled: true,
    intensity: 'HIGH',
  },
  {
    id: 'preset-univ-normal',
    name: 'Normal University Day',
    description: 'Steady background traffic across student dashboard, timetables, and attendance.',
    application: 'student_erp',
    virtualUsers: 50000,
    targetRps: 300,
    durationSeconds: 60,
    trafficPattern: 'NORMAL',
    cacheEnabled: true,
    intensity: 'LOW',
  },
  {
    id: 'preset-crm-peak',
    name: 'CRM Working Hours',
    description: 'Ramp-up during morning business login followed by steady operations and lead creation.',
    application: 'crm',
    virtualUsers: 100000,
    targetRps: 800,
    durationSeconds: 90,
    trafficPattern: 'RAMP_UP',
    cacheEnabled: true,
    intensity: 'MEDIUM',
  },
  {
    id: 'preset-ecom-flash-sale',
    name: 'E-Commerce Flash Sale',
    description: 'Massive surge of traffic searching products, adding to cart, and checking out.',
    application: 'ecommerce',
    virtualUsers: 1000000,
    targetRps: 5000,
    durationSeconds: 180,
    trafficPattern: 'FLASH_SALE',
    cacheEnabled: true,
    intensity: 'EXTREME',
  },
];

export const INFRASTRUCTURE_COMPONENTS: LogicalInfraComponent[] = [
  {
    id: 'comp-cloudfront',
    name: 'CloudFront CDN',
    type: 'CDN / Edge Network',
    category: 'CDN',
    purpose: 'Edge caching, TLS termination, static asset delivery, latency reduction.',
    futureAwsService: 'AWS CloudFront',
    currentLocalEquivalent: 'Local In-Memory static asset & headers caching layer',
    status: 'HEALTHY',
    metrics: { rps: 0, latencyMs: 2, cacheHitRate: 94.5 },
  },
  {
    id: 'comp-waf',
    name: 'Web Application Firewall',
    type: 'WAF & Security Shield',
    category: 'WAF',
    purpose: 'DDoS protection, rate limiting, SQL injection defense, IP filtering.',
    futureAwsService: 'AWS WAF',
    currentLocalEquivalent: 'Fastify Rate Limit & Zod Schema Validation middleware',
    status: 'HEALTHY',
    metrics: { rps: 0, latencyMs: 1, errorRate: 0.1 },
  },
  {
    id: 'comp-alb',
    name: 'Application Load Balancer',
    type: 'Layer 7 Load Balancer',
    category: 'LOAD_BALANCER',
    purpose: 'Distributes incoming HTTP/WS traffic across container instances with health checks.',
    futureAwsService: 'AWS Application Load Balancer (ALB)',
    currentLocalEquivalent: 'Fastify Node.js HTTP Server & Worker Dispatcher',
    status: 'HEALTHY',
    metrics: { rps: 0, latencyMs: 5, activeConnections: 120 },
  },
  {
    id: 'comp-ecs-api',
    name: 'API Service Task Cluster',
    type: 'Containerized Backend API',
    category: 'COMPUTE',
    purpose: 'Hosts control plane REST and WebSocket handlers for simulation & SaaS endpoints.',
    futureAwsService: 'AWS ECS / Fargate Service',
    currentLocalEquivalent: 'Fastify Node.js process (apps/api)',
    status: 'HEALTHY',
    metrics: { rps: 0, latencyMs: 15, activeConnections: 80 },
  },
  {
    id: 'comp-redis',
    name: 'ElasticCache Redis',
    type: 'In-Memory Cache & Pub/Sub',
    category: 'CACHE',
    purpose: 'Caches frequent ERP & E-Commerce responses, handles Pub/Sub live metrics & queues.',
    futureAwsService: 'AWS ElastiCache for Redis',
    currentLocalEquivalent: 'Local Redis Docker Container',
    status: 'HEALTHY',
    metrics: { rps: 0, latencyMs: 3, cacheHitRate: 88.2 },
  },
  {
    id: 'comp-sqs',
    name: 'Simulation Queue',
    type: 'Asynchronous Job Queue',
    category: 'QUEUE',
    purpose: 'Decouples simulation creation requests from execution worker processes.',
    futureAwsService: 'AWS Simple Queue Service (SQS)',
    currentLocalEquivalent: 'Redis List SimulationQueue Abstraction',
    status: 'HEALTHY',
    metrics: { queueDepth: 0 },
  },
  {
    id: 'comp-worker',
    name: 'Simulation Worker Task Cluster',
    type: 'Asynchronous Worker Fleet',
    category: 'WORKER',
    purpose: 'Runs background simulation engines, generates virtual user load and metrics.',
    futureAwsService: 'AWS ECS / Fargate Worker Tasks',
    currentLocalEquivalent: 'Node.js Simulation Worker process (workers/ simulation-worker)',
    status: 'HEALTHY',
    metrics: { rps: 0, latencyMs: 25 },
  },
  {
    id: 'comp-rds',
    name: 'RDS PostgreSQL Database',
    type: 'Relational Database',
    category: 'DATABASE',
    purpose: 'Persistent relational storage for Users, Simulations, ERP, CRM, and E-Commerce schemas.',
    futureAwsService: 'AWS RDS PostgreSQL Multi-AZ',
    currentLocalEquivalent: 'Local PostgreSQL Docker Container',
    status: 'HEALTHY',
    metrics: { activeConnections: 15, latencyMs: 10 },
  },
];
